### ISSUE TITLE
Style hook for `chat-messages` is commented out

### ISSUE THREAD

**Issue by habbes** [jifalops/chat-window#7]
Is there any particular reason why

```css
/*@apply --chat-window-messages;*/
```
is commented out?

I'd like to  add style hooks to the `chat-messages` area of the comment.
As a workaround I've uncommented that line on a fork of this repo, but was curious to find out why you disabled it in the first place.

**Comment by jifalops** [comment]
It's because it was renamed to `--chat-messages` and is used slightly differently. The documentation will be updated soon.

**Comment by habbes** [comment]
Cool, thanks. Looking forward to the update.

**Comment by jifalops** [comment]
Added doc fixes to #0.5.1 (Polymer 1.x based) and released a Polymer 2.0 based hybrid version with #0.6.0. Class-based will be 1.0.
